#!/usr/bin/env python3
"""
make_gauge_bg.py -- render the gauge's STATIC layers to 4bpp BMP files.

Why: the gauge lives in a 240x240 4bpp displayio.Bitmap, 28,800 bytes of
RAM -- by far the largest single allocation on a device that runs at ~37KB
free. But almost none of it is dynamic. The arc and tick marks depend only
on (muted, busy, power_off); the only thing that moves frame to frame is the
pointer. That is the same static/dynamic split dial_ui._scene_signature()
already exploits to skip repaints.

displayio.OnDiskBitmap streams pixel rows off flash during refresh and needs
no RAM for the image -- but it is READ-ONLY, so it cannot back the gauge
bitmap we draw into. It can back the static layer underneath a much smaller
writable bitmap holding just the pointer. This script produces those static
layers so that idea can actually be measured on hardware.

Output is written straight from dial_ui's own index data (via
tools/dial_sim.py's CircuitPython shims), so the asset is generated by the
exact code that renders the gauge today rather than an approximation. 4bpp
indexed, uncompressed, palette taken from dial_ui._PALETTE -- 240px at 4bpp
is 120 bytes per row, already 4-byte aligned, so no row padding is needed.

Usage:
    python tools/make_gauge_bg.py            # -> local/gauge_bg/*.bmp
"""
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import dial_sim  # noqa: E402  (installs CircuitPython shims, imports dial_ui)

dial_ui = dial_sim.dial_ui
OUT_DIR = dial_sim.LOCAL / "gauge_bg"


def _write_bmp4(path, bmp, palette):
    """Write a _FakeBitmap of palette indices as a 4bpp indexed BMP."""
    w, h = dial_ui._W, dial_ui._H
    row_bytes = w // 2                      # 2 px per byte; 120 -> already aligned
    assert row_bytes % 4 == 0, row_bytes
    pixel_bytes = row_bytes * h
    pal_bytes = 16 * 4
    offset = 14 + 40 + pal_bytes

    out = bytearray()
    out += b"BM"
    out += struct.pack("<IHHI", offset + pixel_bytes, 0, 0, offset)
    # BITMAPINFOHEADER. Negative height would mean top-down; BMP's default is
    # bottom-up and OnDiskBitmap handles that, so write rows in reverse.
    out += struct.pack("<IiiHHIIiiII",
                       40, w, h, 1, 4, 0, pixel_bytes, 2835, 2835, 16, 0)
    for i in range(16):
        c = palette[i] if i < len(palette) else 0
        out += bytes(((c) & 0xFF, (c >> 8) & 0xFF, (c >> 16) & 0xFF, 0))  # BGRA

    data = bmp._data
    for y in range(h - 1, -1, -1):          # bottom-up
        base = y * w
        row = bytearray(row_bytes)
        for x in range(0, w, 2):
            hi = data[base + x] & 0x0F
            lo = data[base + x + 1] & 0x0F
            row[x // 2] = (hi << 4) | lo
        out += row

    path.write_bytes(out)
    return len(out)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    palette = dial_ui._PALETTE
    sentinel = dial_ui._SENTINEL   # below _VOL_MIN -> arc + ticks, no pointer

    variants = (
        ("normal",   dict(muted=False, busy=False, power_off=False)),
        ("muted",    dict(muted=True,  busy=False, power_off=False)),
        ("busy",     dict(muted=False, busy=True,  power_off=False)),
        ("power_off", dict(muted=False, busy=False, power_off=True)),
    )

    total = 0
    for name, kw in variants:
        bmp = dial_sim._FakeBitmap(dial_ui._W, dial_ui._H, 16)
        dial_ui._render_gauge(bmp, sentinel, kw["muted"],
                              power_off=kw["power_off"], busy=kw["busy"])
        if not kw["power_off"]:
            dial_ui._draw_menu_home(bmp)
        n = _write_bmp4(OUT_DIR / ("gauge_%s.bmp" % name), bmp, palette)
        total += n
        print("  %-22s %6d bytes" % ("gauge_%s.bmp" % name, n))

    print("\n%d files, %d bytes total on flash" % (len(variants), total))
    print("(each replaces 28,800 bytes of RAM while displayed)")
    print("written to", OUT_DIR.relative_to(dial_sim.ROOT))


if __name__ == "__main__":
    main()
